/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RunCmd */

#ifndef _Included_RunCmd
#define _Included_RunCmd
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RunCmd
 * Method:    runCommand
 * Signature: (Ljava/lang/String;)LCmdResult;
 */
JNIEXPORT jobject JNICALL Java_RunCmd_runCommand
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
